FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o switch ./cmd/switch

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /switch .
EXPOSE 8080
CMD ["./switch"]
