'use client';
import {useEffect,useMemo,useState} from 'react';

export default function MonitorDemo(){
 const [running,setRunning]=useState(true); const [tick,setTick]=useState(0);
 useEffect(()=>{const id=setInterval(()=>setTick(v=>v+1),2000);return()=>clearInterval(id)},[]);
 const pressure=(84.2+Math.sin(tick/2)*1.8).toFixed(1), temp=(72.8+Math.cos(tick/3)*.9).toFixed(1), flow=(62.5+Math.sin(tick/3)*2.2).toFixed(1);
 const series=useMemo(()=>Array.from({length:28},(_,i)=>55+Math.sin((i+tick)*.42)*12+(i%5)*1.2),[tick]);
 return <main><section className="page-head"><div className="container"><span className="eyebrow"><span className="dot"/> Demo · Public preview</span><h1>دموی مانیتورینگ Horizon</h1><p>یک محیط نمایشی عمومی برای دیدن تجربه مانیتورینگ. داده‌های این صفحه نمونه‌اند و به تجهیزات واقعی متصل نیستند.</p></div></section><section className="section"><div className="container demo-layout"><div className="card panel"><div className="toolbar"><div><b>Demo Site / Industrial Unit 01</b><div className="muted small">آخرین به‌روزرسانی: هر ۲ ثانیه</div></div><button className={`btn ${running?'btn-success':'btn'}`} onClick={()=>setRunning(v=>!v)}>{running?'توقف دمو':'اجرای دمو'}</button></div><div className="chart"><svg viewBox="0 0 760 260" preserveAspectRatio="none">{series.map((v,i)=>{const x=i*(760/27), y=220-v*1.3; const prev=i?series[i-1]:v; const px=(i-1)*(760/27), py=220-prev*1.3; return i===0?null:<line key={i} x1={px} y1={py} x2={x} y2={y} stroke="currentColor" strokeWidth="4" strokeLinecap="round"/>})}</svg></div><div className="grid-3 spaced"><div className="metric"><div className="label">Pressure</div><div className="value">{pressure} bar</div><div className="sub">Within demo range</div></div><div className="metric"><div className="label">Temperature</div><div className="value">{temp} °C</div><div className="sub">Within demo range</div></div><div className="metric"><div className="label">Flow</div><div className="value">{flow}</div><div className="sub">Signal stable</div></div></div></div><div className="card panel"><h3 style={{marginTop:0}}>Site status</h3><div className="status-row"><span>Gateway</span><span className="ok-text">● Online</span></div><div className="status-row"><span>Sensor bus</span><span className="ok-text">● Healthy</span></div><div className="status-row"><span>Security event</span><span className="warn-text">● 2 notices</span></div><div className="status-row"><span>Data mode</span><span>Demo</span></div><div className="hr"/><div className="notice">برای محیط واقعی، همین تجربه می‌تواند پشت کنترل دسترسی و در استقرار ایزوله/آفلاین قرار بگیرد.</div><div className="spaced"><b>چه چیزهایی را می‌توان دید؟</b><div className="feature-list" style={{marginTop:8}}><div className="feature"><div className="feature-icon">◎</div><div><b>سنسورها</b><span>Pressure، temperature، flow و readings.</span></div></div><div className="feature"><div className="feature-icon">!</div><div><b>هشدارها</b><span>رخدادهای مهم و نیازمند رسیدگی.</span></div></div><div className="feature"><div className="feature-icon">⌘</div><div><b>وضعیت سایت</b><span>Gateway و مسیر ارتباطی.</span></div></div></div></div></div></div></div></section></main>}
